name: Generate Snake

on:
  schedule:
    - cron: "0 */24 * * *" 
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Commit & Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Updated GitHub contribution snake animation"
          add: "dist/*.svg"
          push: true
